<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_</name>
   <tag></tag>
   <elementGuidId>31adaf24-ebc0-4946-b5f5-7cfa47a3db9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-language-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='icp-language-heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>3c3e79d6-2020-412a-8b73-150ef2b0962f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-language-heading</value>
      <webElementGuid>6f96c18f-9f47-40d8-9903-c9be0b4aaf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-spacing-base</value>
      <webElementGuid>8da26fe8-4aae-4bc8-8068-34ed8c37dd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>भाषा सेटिंग</value>
      <webElementGuid>0519f5d5-98df-457d-8296-85c86de94436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-language-heading&quot;)</value>
      <webElementGuid>f7d912b3-7c59-466a-919c-c6afa58e69ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='icp-language-heading']</value>
      <webElementGuid>b3fa404e-128d-4792-b4dd-c61246e29d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='icp-language-headings']/h3</value>
      <webElementGuid>888b1710-af1b-490f-8661-76606eadcc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>6fea65eb-417d-45b3-b787-91ab89018df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'icp-language-heading' and (text() = 'भाषा सेटिंग' or . = 'भाषा सेटिंग')]</value>
      <webElementGuid>db5661f7-c763-4c4e-a960-a2e89d0824a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
